### ISSUE TITLE
Building from source - daemon

### ISSUE THREAD

**Issue by LiteBit** [vergecurrency/raspi#1]
Following readme.md instructions on rpi wheezy

Getting following error at 
`git clone https://github.com/vergecurrency/verge && cd verge/src && make -f makefile.unix`

> cc1plus: error: unrecognized command line option ‘-msse2’
> Makefile:739: recipe for target 'build/bitcoin.o' failed
> make: **\* [build/bitcoin.o] Error 1

**Comment by vergecurrency** [comment]
fixed! thanks =]
