### ISSUE TITLE
Building from source - GUI

### ISSUE THREAD

**Issue by LiteBit** [vergecurrency/raspi#2]
Following readme.md instructions on rpi wheezy

Getting following error at 
`git clone https://github.com/vergecurrency/verge && cd verge && qmake && make`

> cc1plus: error: unrecognized command line option ‘-msse2’
> Makefile:739: recipe for target 'build/bitcoin.o' failed
> make: **\* [build/bitcoin.o] Error 1

**Comment by vergecurrency** [comment]
fixed, instructions were still cloning main source code repo instead of this one, heh.. fixed. post another issue if you have any more problems though, please =]
